using UnityEngine;
using UnityEngine.InputSystem;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.TextCore.Text;

public class PlayerMovement : MonoBehaviour
{
    private Controller controls;
    private Vector3 velocity;
    private Vector2 move;
    private CharacterController controller;
    private bool isGrounded;

    private float moveSpeed = 10f;
    private float gravity = -9.81f;
    private float jumpHeight = 2.5f;

    public Transform ground;
    public LayerMask groundMask;
    public float distanceToGround = 0.4f;

    private void Awake()
    {
        controls = new Controller();
        controller = GetComponent<CharacterController>();
    }

    // Update is called once per frame
    void Update()
    {
        Gravity();
        Movement();
        JumpH();
    }

    private void Gravity()
    {
        isGrounded = Physics.CheckSphere(ground.position, distanceToGround, groundMask);

        if (isGrounded && velocity.y < 0)
        {
            velocity.y = -2f;
        }

        velocity.y += gravity * Time.deltaTime;
        controller.Move(velocity * Time.deltaTime);
    }

    private void Movement()
    {
        move = controls.Player.Move.ReadValue<Vector2>();

        Vector3 distance = (move.y * transform.forward) + (move.x * transform.right);
        controller.Move(distance * moveSpeed * Time.deltaTime);
    }

    private void JumpH()
    {
        if (controls.Player.Jump.triggered)
        {
            velocity.y = Mathf.Sqrt(jumpHeight * -2f * gravity);
        }
    }

    private void OnEnable()
    {
        controls.Enable();
    }

    private void OnDisable()
    {
        controls.Disable();
    }
}
